services:
  - type: web
    name: manish-kanwar-portfolio
    runtime: docker
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SECURE_SSL_REDIRECT
        value: "True"
