# Generated by Django 5.0.9 on 2026-09-17 00:26

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In Discussion'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('project_type', models.CharField(choices=[('textile_print', 'Textile Print Design'), ('cad', 'CAD Design'), ('surface_pattern', 'Surface Pattern Design'), ('digital_textile', 'Digital Textile Design'), ('motif', 'Motif Development'), ('repeat', 'Repeat Pattern'), ('collection', 'Collection Development'), ('custom', 'Custom Design'), ('other', 'Other')], max_length=30)),
                ('budget_range', models.CharField(blank=True, max_length=80)),
                ('timeline', models.CharField(blank=True, max_length=80)),
                ('project_details', models.TextField()),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='hire_references/')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In Discussion'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Textile Designer & CAD Designer', max_length=200)),
                ('hero_subtitle', models.TextField(default='Creating contemporary textile designs, surface patterns and CAD artwork for fashion and textile applications.', max_length=300)),
                ('hero_badge_text', models.CharField(blank=True, default='2+ Years of Professional Experience', max_length=80)),
                ('hero_primary_cta_text', models.CharField(default='View My Work', max_length=40)),
                ('hero_primary_cta_link', models.CharField(default='/work/', max_length=200)),
                ('hero_secondary_cta_text', models.CharField(default='Hire Me', max_length=40)),
                ('hero_secondary_cta_link', models.CharField(default='/hire/', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/', validators=[apps.core.validators.validate_image_file])),
                ('hero_secondary_image', models.ImageField(blank=True, null=True, upload_to='homepage/', validators=[apps.core.validators.validate_image_file])),
                ('intro_heading', models.CharField(default='Designing Ideas Into Textile Stories.', max_length=200)),
                ('intro_content', models.TextField(default='I am a Textile Designer and CAD Designer with 2+ years of professional experience creating textile prints, surface patterns and digital design concepts. My work combines creative exploration with an understanding of contemporary trends, visual balance and practical textile applications.')),
                ('work_section_heading', models.CharField(default='Selected Work', max_length=120)),
                ('work_section_subtitle', models.CharField(default='A curated selection of textile designs developed across different styles, techniques and applications.', max_length=240)),
                ('final_cta_heading', models.CharField(default='Have a Textile Design Project in Mind?', max_length=200)),
                ('final_cta_description', models.TextField(default="Whether you need a custom textile print, surface pattern, CAD artwork or a complete design direction, let's discuss your requirements.")),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Manish Kanwar', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Textile Designer & CAD Designer', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.core.validators.validate_image_file])),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.core.validators.validate_image_file])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^[0-9+\\-\\s()]{7,20}$')])),
                ('location', models.CharField(blank=True, help_text='e.g. Jaipur, Rajasthan, India', max_length=120)),
                ('cv_file', models.FileField(blank=True, help_text="PDF shown behind the 'Download CV' button.", null=True, upload_to='documents/', validators=[apps.core.validators.validate_cv_file])),
                ('open_to_freelance', models.BooleanField(default=False, help_text="Shows the 'currently open to freelance projects' note in the hero.")),
                ('available_for_opportunities', models.BooleanField(default=False, help_text="Shows the 'Available for Professional Opportunities' section site-wide.")),
                ('default_seo_title', models.CharField(blank=True, max_length=70)),
                ('default_seo_description', models.CharField(blank=True, max_length=160)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='site/', validators=[apps.core.validators.validate_image_file])),
                ('google_analytics_id', models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX', max_length=32)),
                ('google_search_console_code', models.CharField(blank=True, max_length=200)),
                ('footer_note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('behance', 'Behance'), ('pinterest', 'Pinterest'), ('facebook', 'Facebook'), ('email', 'Email'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(blank=True, help_text="Optional custom label, e.g. 'Behance'", max_length=60)),
                ('url', models.URLField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=120)),
                ('author_role', models.CharField(blank=True, help_text='Role / company', max_length=160)),
                ('quote', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[apps.core.validators.validate_image_file])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
