# Generated by Django 5.0.9 on 2026-09-17 00:26

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='categories/', validators=[apps.core.validators.validate_image_file])),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('short_description', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True, help_text='Longer, SEO-friendly project overview shown on the project page.')),
                ('design_type', models.CharField(blank=True, max_length=120)),
                ('technique', models.CharField(blank=True, max_length=120)),
                ('application', models.CharField(blank=True, max_length=120)),
                ('style', models.CharField(blank=True, max_length=120)),
                ('software', models.CharField(blank=True, max_length=120)),
                ('color_direction', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='portfolio.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.tag')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/', validators=[apps.core.validators.validate_image_file])),
                ('image_type', models.CharField(choices=[('main', 'Main Design'), ('motif', 'Motif'), ('top', 'Top / Placement'), ('bottom', 'Bottom / Border'), ('border', 'Border'), ('repeat', 'Repeat / Surface'), ('detail', 'Detail'), ('back', 'Back'), ('side', 'Side'), ('colorway', 'Colorway'), ('mockup', 'Mockup'), ('other', 'Other')], default='detail', max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('alt_text', models.CharField(blank=True, help_text="Descriptive alt text for SEO/accessibility, e.g. 'Floral botanical surface pattern textile design'.", max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'is_featured'], name='portfolio_p_is_publ_674f93_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('category', 'slug')},
        ),
    ]
